[package]
name = "fit_kit"
version = "0.1.0"
edition = "2021"
authors = ["29decibel <m@idots.me>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
fitparser = "0.9.0"
magnus = { version = "0.7.1" }
